### ISSUE TITLE
auth settings - no existing config detected

### ISSUE THREAD

**Issue by t3kg33k** [csmart/korora-ansible#2]
Maybe I am doing something wrong...
Here's the error I receive when executing the run.sh script:

TASK [ansible-role-korora : Get current auth settings] ***********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["authselect", "current"], "delta": "0:00:00.004666", "end": "2020-02-11 03:31:18.646930", "msg": "non-zero return code", "rc": 2, "start": "2020-02-11 03:31:18.642264", "stderr": "", "stderr_lines": [], "stdout": "No existing configuration detected.", "stdout_lines": ["No existing configuration detected."]}

I'm running against localhost. No other changes. My steps in my attempt are as follows per your instructions:
1. clone the git repository
git clone --recursive https://github.com/csmart/korora-ansible
2. Change to the korora-ansible directory and run the shell script.

Am I doing something wrong? This is running against a vanilla install of Fedorar 31 install from a Kickstart script I created with Ansible installed.
I miss the Korora distribution a lot and all I am trying to do is get back to a Fedora install that is as close to the look and feel of Korora as possible.
Thanks.

**Comment by csmart** [comment]
Hmm.. I just spun up Fedora 31 cloud image, installed authselect and ran it, it seems to work.

[csmart@example-fedora-31 ~]$ sudo authselect current
Profile ID: sssd
Enabled features: None

Could you please try running that command manually on the terminal and let me know what happens?

**Comment by t3kg33k** [comment]
Authselect is installed on the VM I am testing.

_ed@localhost ~]$ sudo authselect current
No existing configuration detected._

**Comment by csmart** [comment]
OK, interesting... is that Fedora 31? What image are you using in the VM?

**Comment by t3kg33k** [comment]
Fedora 31 from Net install

**Comment by csmart** [comment]
OK let me see if I can replicate...

**Comment by csmart** [comment]
OK can you try changing the ansible role to a branch with a fix to test? Assuming you're inside the korora-ansible directory, go into the role dir, pull the latest changes and checkout the branch, then run the run.sh script again:

```bash
cd roles/ansible-role-korora/
git fetch --all
git checkout fix-authselect
cd ../../
./run.sh
```

**Comment by csmart** [comment]
I just installed Fedora 31 via net install and it works for me, so I don't quite know why it's not working for you...

```bash
[csmart@localhost ~]$ sudo authselect current
Profile ID: sssd
Enabled features:
- with-fingerprint
- with-silent-lastlog
```

**Comment by csmart** [comment]
Anyway, if you can try that patch and let me know. If it works I can merge it.

**Comment by t3kg33k** [comment]
Looks like your fix worked. Thanks for looking into that.

It all works beautifully. Thanks again. So freakin cool. Korora lives on!

**Comment by csmart** [comment]
Great! No worries, thanks for letting me know.
